### ISSUE TITLE
Support avro spec v1.x.x

### ISSUE THREAD

**Issue by germanschnyder** [asyncapi/avro-schema-parser#10]
#### Reason/Context
As avro schema doesn't include breaking changes the avro schema parser should support all schemas . 

#### Description
Mimetypes have to be adjusted to include matching versions
Consider minor adjustments between versions.

**Comment by derberg** [comment]
@germanschnyder is it something we can count on you with? tbh doesn't look like many people look for it, and also hard to find expert of avro among maintainers

**Comment by germanschnyder** [comment]
I will try to set aside some time to contribute or at least to provide an analysis for this feature

**Comment by derberg** [comment]
I'll close for now, and feel free to reopen when you want to work on it. We lack proper expert knowledge to add it on our own, so looking for contributions.
