### ISSUE TITLE
Missing local reference usage in doc

### ISSUE THREAD

**Issue by M3lkior** [asyncapi/avro-schema-parser#12]
#### Describe the bug
Usage with remote references is documented but not for local references (files directly present in project)

#### How to Reproduce
See the actual documentation

#### Expected behavior
Add a chapter for local reference example : 

```
const parser = require('@asyncapi/parser')
const avroSchemaParser = require('@asyncapi/avro-schema-parser')

parser.registerSchemaParser(avroSchemaParser)

const asyncapiWithAvro = `
asyncapi: 2.0.0
info:
  title: Example with Avro
  version: 0.1.0
channels:
  example:
    publish:
      message:
        schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
        payload:
          $ref: 'loca/path/to/file/user'
`

await parser.parse(asyncapiWithAvro)
```

**Comment by derberg** [comment]
@M3lkior makes a lot of sense, could you open a pull request and add such a section called `Usage with local references`?

This repo has `hacktoberfest` topic so the PR will count in with https://hacktoberfest.digitalocean.com/

**Comment by M3lkior** [comment]
Yeah sure :) could you add the Hacktoberfest label ?

**Comment by derberg** [comment]
@M3lkior done, but I don't think it is needed, just the repo needs a topic

**Comment by derberg** [comment]
@M3lkior hey, wanted to check with you if you plan to work on this one or should I pass it to other Hacktoberfest contributors?

**Comment by M3lkior** [comment]
You can assign this issue to another Hacktoberfest contributor because i can not contribute on issue open by me :p

**Comment by derberg** [comment]
@M3lkior oh, I had no idea there is such a rule 😄

**Comment by bszwarc** [comment]
@derberg I will help with this :)
