### ISSUE TITLE
[New Doc 📑]: Usage with other schema registries

### ISSUE THREAD

**Issue by dalelane** [asyncapi/avro-schema-parser#123]
### What Dev Docs changes are you proposing?

The README includes guidance for using avro-schema-parser with Confluent's schema registry (https://github.com/asyncapi/avro-schema-parser#usage-with-confluent-schema-registry)

I think it would be a good improvement to include similar guidance for other schema registries. 

I could add a few:
- [Apicurio](https://www.apicur.io/registry/docs/apicurio-registry/2.1.x/index.html)
- [Event Streams (on-prem)](https://ibm.github.io/event-streams/schemas/overview/)
- [Event Streams (cloud)](https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-ES_schema_registry)

It'd be great to have more though.

If this starts making the README a little too long, we might want to break these out to a separate page. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by derberg** [comment]
It makes a lot of sense imho. Would be even nice to turn it into a set of tutorials under official documentation. So the once added here would be like an technical input that later @alequetzalli could include in official documentation, because these guides are not really only about Avro parser.

When you add another guide, I think we should integrate ToC generation as we do in other projects using https://github.com/asyncapi/generator/blob/master/package.json#L91 and then we automatically regenerate when needed with https://github.com/asyncapi/generator/blob/master/package.json#L27

**Comment by alequetzalli** [comment]
Hey @dalelane, thank you for your suggestion and interest in contributing to the README doc for describing the usage of other schema registries. I agree with what @derberg mentions, about how you are describing improving a repo README vs adding a new doc to the official `/Docs`. 

When you put up a PR for your additions, I can re-purpose your content into official Docs for our Docs site, like Lukasz also suggested. 😀👍🏽👍🏽 

I look forward to following this issue and your PRs, let me know what you think! ✨✨✨

**Comment by dalelane** [comment]
capturing some links for myself to use in a first draft

- IBM Event Streams (managed cloud service)
    - create an API key - https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-ES_schema_registry#accessing_schema_registry
    - get URL for a schema - https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-ES_schema_registry#getting-a-specific-version-of-a-schema
- IBM Event Streams (on-premise / container-native software)
    - create an API key - https://ibm.github.io/event-streams/security/managing-access/#managing-access-to-kafka-resources
    - get URL for a schema - 
- Apicurio
    - get URL for a schema - https://www.apicur.io/registry/docs/apicurio-registry/2.1.x/assets-attachments/registry-rest-api.htm#operation/getArtifactVersion
