### ISSUE TITLE
"bidnings.kafka.key" is transformed even if schema is defined as JSON Schema

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/avro-schema-parser#139]
#### Describe the bug

`bidnings.kafka.key` field is transformed by `avro-parser` even if schema is defined as JSON Schema, but it should be only when is defined as Avro Schema.

#### How to Reproduce

Paste to [the Studio](https://studio.asyncapi.com/) example spec with `bindings.kafka.key`:

```yaml
asyncapi: 2.3.0
info:
  title: Generic title
  version: '0.0.1'
  description: Generic description

channels:
  kafka-topic-name:
    publish:
      message:
        oneOf:
          - name: SessionCreated
            schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
            bindings:
              kafka:
                key:
                  type: string
                  description: Here we go
                  enum: [ 'sessionId' ]
                bindingVersion: '0.2.0'
            payload:
              $ref: '#/components/x-avro-schemas/SessionCreated'

components:
  x-avro-schemas:
    SessionCreated:
      {"namespace": "example.avro",
       "type": "record",
       "name": "User",
       "fields": [
         {"name": "name", "type": "string"},
         {"name": "favorite_number",  "type": ["int", "null"]},
         {"name": "favorite_color", "type": ["string", "null"]}
       ]
      }
```

and you will see:

![image](https://user-images.githubusercontent.com/20404945/162785649-65f9eab6-eb37-421c-a058-1191b0544436.png)

but it should be (I changed `kafka.key` to `kafka.test`):

![image](https://user-images.githubusercontent.com/20404945/162785845-a99da347-e7dc-49d2-9afc-01946e560e77.png)

**Comment by M3lkior** [comment]
@magicmatatjahu this is a side effect of the basic support of Avro definition in the key bindings, described [here](https://github.com/asyncapi/avro-schema-parser/pull/77). Should we wait for any progress on [your proposal](https://github.com/asyncapi/spec/issues/622 ) ? or find a workaround to fix this issue like parsing the entire structure to detect if it is a avro or json definition ?

**Comment by magicmatatjahu** [comment]
@M3lkior Sorry for delay response, I was on vacation.

> this is a side effect of the basic support of Avro definition in the key bindings, described https://github.com/asyncapi/avro-schema-parser/pull/77. Should we wait for any progress on https://github.com/asyncapi/spec/issues/622 ? or find a workaround to fix this issue like parsing the entire structure to detect if it is a avro or json definition ?

I understand, thanks. I don't know when that proposal will be accepted (or even accepted), so I won't count on that. As I see we can check if given schema is avro schema like here https://github.com/asyncapi/avro-schema-parser/blob/master/to-json-schema.js#L271 and make simple try catch for that:

```js
try {
  validateAvroSchema(message.bindings.kafka.key);
} catch(e) {
  // do nothing
}
``` 

but we need to remember that then only JSON Schema will be then accepted.

WDYT?
