### ISSUE TITLE
Manage reference to object declared previously in avro schema

### ISSUE THREAD

**Issue by cmontois** [asyncapi/avro-schema-parser#148]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
To have a better generated documentation

See below: I have 3 type of pallet in my AVRO schema, they use the same object which is declared in the first pallet (transportedPallet)

`
                            {
                               "name":"transportedPallet",
                               "type":[
                                  "null",
                                  {
                                     "namespace":"com.org.service.entity.model.type",
                                     "name":"Pallet",
                                     "type":"record",
                                     "fields":[
                                        ....
                                     ],
                                     "doc":""
                                  }
                               ],
                               "doc":"***",
                               "default":null
                            },
                            {
                               "name":"storagePallet",
                               "type":[
                                  "null",
                                  "com.org.service.entity.model.type.Pallet"
                              ],
                               "doc":"***",
                               "default":null
                            },
                            {
                               "name":"deliveryPallet",
                               "type":[
                                  "null",
                                  "com.org.service.entity.model.type.Pallet"
                               ],
                               "doc":"***",
                               "default":null
                            }
`
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/12199643/168546001-957bed9e-a1ef-4ea4-ba71-d5d1fb872171.png">

- How will this change help?
The documentation will be more accurate for the user.

- What is the motivation?

**Comment by magicmatatjahu** [comment]
Similar problem https://github.com/asyncapi/community/issues/355#issuecomment-1123339481

**Comment by dalelane** [comment]
@cmontois Thanks for pointing this out

Do you have an example AsyncAPI doc that demonstrates the problem that we could use to speed up developing and testing a fix for this please? (The one you've got in the screenshot would probably be good, if you're able to share it)

**Comment by cmontois** [comment]
I created a [gist](https://gist.githubusercontent.com/cmontois/31cad92e79d4ae6d8cd420aeff2332af/raw/dccf33e60ec8fe53af29a300ff8e1579adf9ea2b/avsc_with_reference.avsc)
and here is the doc file so you can reproduce in async API Studio

```
asyncapi: 2.1.0
info:
  title: TEST API
  version: 'Tutu'

channels:
  test-topic:
    description: "Test"

components:
  messages:
    test:
      name: test
      title: Test
      summary: Test
      schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
      payload:
        $ref: 'https://gist.githubusercontent.com/cmontois/31cad92e79d4ae6d8cd420aeff2332af/raw/dccf33e60ec8fe53af29a300ff8e1579adf9ea2b/avsc_with_reference.avsc'
```

**Comment by GDURIS** [comment]
Hi,
Do you have a resolution date to share whith us ?

**Comment by dalelane** [comment]
@GDURIS - sorry, I haven't had any time to work on this yet

**Comment by M3lkior** [comment]
Hi guys (cc @GDURIS  / @cmontois ) , i start implementing this feature as a DRAFT Pr (that actually works) but i need to write some unit tests to finalize it.

Here is a rendering preview: 

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/5501911/183102013-5edff2a7-fca3-4866-82bb-f262e7269092.png">
