### ISSUE TITLE
 Cannot read property 'type' of undefined - using type array in avro schema

### ISSUE THREAD

**Issue by M3lkior** [asyncapi/avro-schema-parser#15]
#### Describe the bug

Based on the `asvc` file below, the generator throws a 
```
Something went wrong:
Error: Cannot read property 'type' of undefined

```
#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:

Here is the Gist with the `asvc` sample : https://gist.github.com/M3lkior/e282c8ebd3ac94759d4f58ebefdb8f49

* Use the https://gist.github.com/M3lkior/e282c8ebd3ac94759d4f58ebefdb8f49#file-asyncapi-yaml file and replace the asvc `$ref` by https://gist.github.com/M3lkior/e282c8ebd3ac94759d4f58ebefdb8f49#file-test-array-avsc

* Run `ag asyncapi.yaml @asyncapi/html-template `

* See the error below : 

```
Something went wrong:
Error: Cannot read property 'type' of undefined

```
#### Expected behavior

* `array` type on avro schema, with `"items": "string"`  must be converted to the HTML element, **for the file test-array.avsc definition**

![image](https://user-images.githubusercontent.com/5501911/95463394-fc62f000-0978-11eb-8f36-9fcb8bf626f3.png)

* `array` type on avro schema, with `"items": "record"`  must be converted to the HTML element, **for the file test-array-record.avsc definition**

![image](https://user-images.githubusercontent.com/5501911/95464132-e275dd00-0979-11eb-8152-d5ca8f7fe49b.png)

**Comment by derberg** [comment]
@M3lkior I transferred the issue as it is avro schema parser related.

I tried one of the examples (you have an error in one JSON in gist):
```
asyncapi: 2.0.0
info:
  title: Test Async API
  version: '0.1.0'
 

channels:
  example:
    publish:
      message:
        schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
        payload:
          type: record
          name: Type Array with Record items not working
          namespace: test
          version: 1
          fields:
          - name: MyArray
            type: array
            doc: Array docs
            items:
              name: ArrayContent
              type: record
              fields:
              - name: FIELD1
                type: string
                doc: doc 1
              - name: FIELD2
                type: string
                doc: doc 2
              - name: FIELD3
                type: string
                doc: doc 3
              - name: FIELD4
                type: boolean
                doc: doc 4
```

the problem is related to how `record` type is handled -> https://github.com/asyncapi/avro-schema-parser/blob/master/to-json-schema.js#L72. Type is passed to `avroToJsonSchema` function, instead of basically array items, so here https://github.com/asyncapi/avro-schema-parser/blob/master/to-json-schema.js#L64 undefined is passed. 

I do not know much about avro, so don't know much about `record` type and what cases should we handle there. Need some support

**Comment by M3lkior** [comment]
@derberg , thanks for the reply.

Except for the `record` type, which is more complexe, the same issue occurs when using the simple `string` type. It could be a good start to solve the issue.

For `avro`, you need some support from who ? the `avro-parser` maintainers ?

**Comment by derberg** [comment]
I think the other example has the same issue, `record` with `array`

```
asyncapi: 2.0.0
info:
  title: Test Async API
  version: '0.1.0'
 

channels:
  example:
    publish:
      message:
        schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
        payload:
          type: record
          name: Type Array not working
          namespace: test
          version: 1
          fields:
          - name: MyArray
            type: array
            doc: Array Docs
            items: string
```

> For avro, you need some support from who ? the avro-parser maintainers ?
I need one of:
- my own education is needed, so support of time 😄 
- or maybe @fmvilas knows exactly how to approach it
- or maybe you know exactly how that should work

**Comment by M3lkior** [comment]
@derberg , i know that the record structure i my Gist is correct and work with the Avro java tools like maven plugins or Kafka Schema Registry.

So i think that this structure : 

```
 // 20201009164810
// https://gist.githubusercontent.com/M3lkior/e282c8ebd3ac94759d4f58ebefdb8f49/raw/b2857b3bb0ceb5ef36733f708051e2480318c5c6/test-array-record.avsc

{
  "type": "record",
  "name": "Type Array with Record items not working",
  "namespace": "test",
  "version": 1,
  "fields": [
    {
      "name": "MyArray",
      "type": {
        "type": "array",
        "doc": "Array docs",
        "items": {
          "name": "ArrayContent",
          "type": "record",
          "fields": [
            {
              "name": "FIELD1",
              "type": "string",
              "doc": "doc 1"
            },
            {
              "name": "FIELD2",
              "type": "string",
              "doc": "doc 2"
            },
            {
              "name": "FIELD3",
              "type": "string",
              "doc": "doc 3"
            },
            {
              "name": "FIELD4",
              "type": "boolean",
              "doc": "doc4"
            }
          ]
        }
      }
    }
  ]
}
```

Should be equals to this AsyncAPI definition : 
``` 
Test2:
      type: object
      properties:
        MyArray:
          type: array
          items:
            type: "object"
            properties:
              FIELD1:
                type: "string"
                description: "doc 1"
              FIELD2:
                type: "string"
                description: "doc 2"
              FIELD3:
                type: "string"
                description: "doc 3"
              FIELD4:
                type: "string"
                description: "doc 4"
```

Maybe @fmvilas can validate this point

**Comment by M3lkior** [comment]
Very sorry @derberg; I came back to my specification after having deepened the `avro` spec and my `avro` schema was wrong,

After refactoring my schema, the generation for array type is good !
