### ISSUE TITLE
Add the ability to import AVRO definition

### ISSUE THREAD

**Issue by M3lkior** [asyncapi/avro-schema-parser#20]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?

Complexe Avro definitions force developers to externalize common record declarations. Like the `avro-maven-plugin` and the `import` configuration, it will be nice to have the ability to import common definitions for `asvc` refs

Here is the `avro-maven-plugin` approach : https://www.nerd.vision/post/reusing-schema-definitions-in-avro

- How will this change help?

This allow us to eliminate code duplication by declaring common definitions

- What is the motivation? 

#### Description
Please try answering few of those questions
- What changes have to be introduced?

The possibility to import common definitions, reusable on avro definitions

- Will this be a breaking change?

No

- How could it be implemented/designed?

Like `schemaFormat: 'application/vnd.apache.avro;version=1.9.0'`, maybe add a `schemaImports` property

**Comment by derberg** [comment]
@M3lkior I'm not sure this is a good place for this issue. It is not only avro related, it is more about extending spec by a new property, right? how are you handling this case without this atm?

**Comment by M3lkior** [comment]
yes maybe this is just about a specification enhancement with an attribute to allow asyncapi file inclusion (and also `asvc` imports)

**Comment by derberg** [comment]
no followup, feel free to reopen when needed
