### ISSUE TITLE
Add Avro Schema Validation

### ISSUE THREAD

**Issue by JQrdan** [asyncapi/avro-schema-parser#37]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
  - This improvement would keep the behaviour of the parsers consistent with each other
- How will this change help?
  - It means that consumers of the parser will not have to rely on their own Avro validation  
- What is the motivation? 
  - All the over parsers in the AsyncApi library validate json schemas, it would be nice if it validated Avro too. This way, parser is responsible for all validation and then can be used straight away

#### Description
Please try answering few of those questions
- Will this be a breaking change?
  - Hopefully not 
- How could it be implemented/designed?
  - Similar to how the json validation is done with other parsers

**Comment by derberg** [comment]
@JQrdan did you plan to work on this. I'm not sure from the description how would you see it works. Are there some js avro validators you know that could be integrated?

**Comment by JQrdan** [comment]
@derberg Unfortunately not. I'm not aware of any reputable Avro validators out there for JS but wanted to raise the issue to see if there were any plans/thoughts about this kind of thing given that everything else is validated 😄

**Comment by dalelane** [comment]
https://github.com/mtth/avsc looks pretty good

@JQrdan - think this would cover what you had in mind?

```js
const assert = require('assert');

// npm install avsc
const avro = require('avsc');

// -------- TEST SCHEMAS -------------------------------------------

const VALID_SCHEMA = {
    type : 'record',
    fields : [
        { name : 'test', type : 'string' }
    ]
};

const INVALID_SCHEMA = {
    type : 'record',
    fields : [
        { name : 'test', type : 'fish' }
    ]
};

const NOT_EVEN_CLOSE = {
    hello : 'world'
};

// -------- PARSING THE TEST SCHEMAS -------------------------------------------

const type = avro.Type.forSchema(VALID_SCHEMA);
assert(type);

try {
    const type2 = avro.Type.forSchema(INVALID_SCHEMA);
    assert.fail();
}
catch (err) {
    assert(err);
}

try {
    const type3 = avro.Type.forSchema(NOT_EVEN_CLOSE);
    assert.fail();
}
catch (err) {
    assert(err);
}
```

**Comment by M3lkior** [comment]
your library seems to be the work @dalelane. Have you tried to define an avro schema with additional attributes to test if the validation passed ?
This is required to keep this feature (#82) already works =)

**Comment by dalelane** [comment]
@JQrdan - would you like to review https://github.com/asyncapi/avro-schema-parser/pull/96 and check it was what you were expecting?
