### ISSUE TITLE
Support inlined schemas

### ISSUE THREAD

**Issue by nictownsend** [asyncapi/avro-schema-parser#39]
Caveat - I am assuming it is valid to inline an Avro schema as a multiline string in an AsyncAPI spec

#### Reason/Context
- The AsyncAPI spec suggests that `message.payload` can be `any` type
- If you inline your avro schema as a JSON string, it should be parsed

#### Description
- When the payload is checked to be a string, if it fails the type lookup then a JSON parse will test if it's an object

**Comment by derberg** [comment]
I have a feeling I had similar discussion with someone somewhere. I don't believe spec suggest payload can be a string that we should parse in the parser

**Comment by nictownsend** [comment]
So currently, if I put a string, the parser will attempt to parse it as an Avro literal type (eg 'string', 'boolean') - which is valid Avro. I'm happy for that behaviour to stay as is, with the expectation that a complex schema can only come in as an object.

**Comment by derberg** [comment]
I'm not 100% sure your statement is valid. Is this what we are talking about:

```
asyncapi: 2.0.0
info:
  title: Example with Avro
  version: 0.1.0
channels:
  example:
    publish:
      message:
        schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
        payload: |
          type: record
          doc: User information
          fields:
            - name: displayName
              type: string
            - name: email
              type: string
            - name: age
              type: int
```

this will not work with the current Avro parser will get a string [here](https://github.com/asyncapi/avro-schema-parser/blob/81e3330faf5514c8713e71e9def5433e13ac677f/to-json-schema.js#L24) and there is no logic to discover that and parse to object

**Comment by nictownsend** [comment]
We're in agreement - what I meant was that https://github.com/asyncapi/avro-schema-parser/blob/81e3330faf5514c8713e71e9def5433e13ac677f/to-json-schema.js#L40 supports a string as the payload because it is still valid Avro.

e.g

```
asyncapi: 2.0.0
info:
  title: Example with Avro
  version: 0.1.0
channels:
  example:
    publish:
      message:
        schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
        payload: 'long'
```

Will be correctly parsed by the parser.

But as you've mentioned - there is no parsing of that string into an object - and I've closed this issue because it assumed that 

```
asyncapi: 2.0.0
info:
  title: Example with Avro
  version: 0.1.0
channels:
  example:
    publish:
      message:
        schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
        payload: |
          type: record
          doc: User information
          fields:
            - name: displayName
              type: string
            - name: email
              type: string
            - name: age
              type: int
```
is valid (it passes the AsyncAPI schema validation as `message.payload` can be `any`) - but as has been clarified, a complex schema should only come in as a YAML object, as it makes no sense to inline into a document you're writing yourself!
