### ISSUE TITLE
Schema Registry $ref not working as expected

### ISSUE THREAD

**Issue by M3lkior** [asyncapi/avro-schema-parser#65]
#### Describe the bug

Using the capabilities of using a schema registry kafka url, my payload is not filled as expected : 

![image](https://user-images.githubusercontent.com/5501911/129359002-480c50af-9b40-4111-9062-39790ac93ba4.png)

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:

You should generate an html page based on this specification (with a correct schema registry url ...) 

```
asyncapi: 2.0.0
info:
  title: Example with Avro
  version: 0.1.0
channels:
  example:
    publish:
      message:
        schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
        payload:
          $ref: 'https://LY422RBU2HN6JQ5T:+f8wz9a0iM06AX7xfwbzSM9YPw/JIkr22Cvl5EKT5Hb1d/nz5nOpbXV/vZC+Iz5c@example.europe-west3.gcp.confluent.cloud/subjects/test/versions/1/schema'
```
 (you can use the OSS https://github.com/apicurio/apicurio-registry if needed)

#### Expected behavior

The payload description should be displayed as expected as a `avsc` local reference $ref. The sample below is a local copy of the schema registry url i try to use

![image](https://user-images.githubusercontent.com/5501911/129359729-9143325b-26c5-4f7a-b953-6d45c69199cf.png)

**Comment by jonaslagoni** [comment]
@M3lkior the schema that is stored, can you provide the output when you manually try to access your URL? It could look like the schema is incorrectly structured somehow.

**Comment by M3lkior** [comment]
sure 

```
{
  "subject": "enterprise-subject-PRODUCT-V1-value",
  "version": 1,
  "id": 101188,
  "schema": "{\"type\":\"record\",\"name\":\"Product\",\"namespace\":\"com.sample.kafka.model.V2\",\"fields\":[{\"name\":\"productId\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}"
}
```

**Comment by M3lkior** [comment]
Outch, my bad, missing to add the `/schema` at the end of the url 😱

**Comment by jonaslagoni** [comment]
> Outch, my bad, missing to add the `/schema` at the end of the url 😱. Maybe the parser should display an appropriate message is the payload is not parsable ? (which is not the case today)

@M3lkior if you feel that would be useful (sounds like it could) feel free to create a new issue 👍
