### ISSUE TITLE
Avro union not displayed correctly in the bindings bloc

### ISSUE THREAD

**Issue by M3lkior** [asyncapi/avro-schema-parser#67]
I use the avro-parser (usage of `avsc` files) in the AsyncAPI specification for my kafka messages payload and key

When i use a record definition with union fields (like `"type": ["null", { "type": "string",  "avro.java.string": "String" }]` or "type": ["null", { "type": "int" }], the definition is not correctly displayed : 

![image](https://user-images.githubusercontent.com/5501911/129583865-e5980bea-84fb-44d4-b90f-1c56f77df27b.png)

**Expected result**

The display should be like the payload part (actually working like a charm with avro files):

![image](https://user-images.githubusercontent.com/5501911/129584111-c799a670-ffa2-4acf-933d-e8008f58fa9a.png)
  
> the record type is not handle 

**Actual result**

![image](https://user-images.githubusercontent.com/5501911/129583865-e5980bea-84fb-44d4-b90f-1c56f77df27b.png)

**Steps to reproduce**

- The avro schema definition : 
```
{
  "namespace": "sample",
  "type": "record",
  "name": "SampleRecord",
  "version": 1,
  "fields": [
    {"name": "NoUnionField", "type": { "type": "string",  "avro.java.string": "String" }, "doc": "Any doc"},
    {"name": "UnionField", "type": ["null", { "type": "string",  "avro.java.string": "String" }], "doc": "any doc"}
  ]
}

```

- the spec file with avro reference : 
```
asyncapi: '2.1.0'
id: 'urn:adeo:dev:euw1:sample'
info:
  version: ''
  description: 

channels:
  test:
    subscribe:
      summary: Get updated products
      message:
        $ref: "#/components/messages/example-value"

components:
  messages:
    example-value:
      schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
      payload:
        $ref: "SampleRecord.avsc" 
      bindings:
        kafka:
          key: 
            $ref: "SampleRecord.avsc" 


```

**Troubleshooting**

**Comment by magicmatatjahu** [comment]
The problem is that we don't support the transforming of schemas in other places (like bindings) than `message.payload` -> https://github.com/asyncapi/avro-schema-parser/blob/master/index.js#L4

**Comment by M3lkior** [comment]
hi @magicmatatjahu  ; thanks for the reply ! it is clear and precise ! i hope this issue will be resolved soon :)

**Comment by M3lkior** [comment]
i will take this issue and do a PR proposal :)

**Comment by M3lkior** [comment]
hi @magicmatatjahu @fmvilas @derberg  ; i submit a first proposal of the avro bindings bloc support but only for the `kafka.key` part.

Have you a good approach to easily handle all the bindings protocol ? like do a search on a json object to detect the `avsc ` ref and deduce the json object subpath concerned ?
