### ISSUE TITLE
The Avro Schema 'name' field should get carried over to the JSON Schema 'title' field.

### ISSUE THREAD

**Issue by damaru-inc** [asyncapi/avro-schema-parser#68]
#### Describe the bug
When you use an Avro schema in an AsyncAPI document and run it through the parser, the resulting schema has no 'title' attribute set even when the Avro schema had a 'name' attribute.

The schema is presented by the parser as having a name like <anonymous-schema-1>, but it would be nice for code generators to be able to get the original name somehow.

#### How to Reproduce
Run the test in this project, you'll see that the 'transforms record values' confirms that no title field appears.

#### Expected behavior
I would have expected to see the 'name' attribute copied to the 'title' attribute in the generated JSON schema.

**Comment by derberg** [comment]
@damaru-inc `title` will not help much - [have a look](https://github.com/asyncapi/parser-js/blob/master/lib/models/schema.js#L23)

the only way to get nice name instead of anonymous name is to get the `name` into `$id`, the question is: is Avro `name` suited for JSON Schema `$id`

cc @fmvilas

**Comment by damaru-inc** [comment]
Why do you say that 'title' won't help? I don't think $id is appropriate, because in json schema, the $id field is supposed to be a URI that uniquely identifies the schema, whereas 'title' seems to serve the same purpose as the avro 'name' field. Avro schemas can have ids, but they usually aren't represented in the schema itself, they're often used by kafka to fetch a schema from a schema registry to serialize/deserialize a message. So that would be another thing that would cause confusion, i.e. if we take the avro name and have it come back as an $id property of the resulting json schema.
