### ISSUE TITLE
improve project maintainance

### ISSUE THREAD

**Issue by derberg** [asyncapi/avro-schema-parser#90]
@M3lkior @dalelane

me and @fmvilas are super loaded and I notice we are blocking quite often any changes to avro parser. 

@M3lkior you've put together few PRs already here and have a good understanding of the project. @dalelane you are also experienced with Kafka and therefore Avro and often help with reviews and I bet that on a code level that would also not be a big problem.

would you folks be ok to become maintainers here, part of CODEOWNERS file?
I would stay there with @fmvilas for a while in case we are needed, until the group gets larger and there is no risk that PRs will hang forever.

it means:
- you are invited to have `write` access in the repo
- you can accept/reject changes in bindings that you own 
- you must of course follow code of conduct, that you already follow
- you need to help with reviews of PRs related to bindings that you own

Last but not least, because you become a maintainer, you MAY also join the [TSC of AsyncAPI Initiative](https://www.asyncapi.com/community/tsc) 

What do you think? I personally would be super happy to see in a maintainer and TSC member position!

**Comment by dalelane** [comment]
@derberg yeah, sure - I'd be happy to
