### ISSUE TITLE
Improve example schemas in tests to make examples consistent with spec

### ISSUE THREAD

**Issue by dalelane** [asyncapi/avro-schema-parser#97]
identified in https://github.com/asyncapi/avro-schema-parser/pull/96#discussion_r749167969 

Some of the schemas in the tests folder have int data types but string examples. This doesn't break anything, but it would be good to tidy this up and update examples so that they are correctly typed.

**Comment by etolbakov** [comment]
improved this bit with https://github.com/asyncapi/avro-schema-parser/pull/99

**Comment by dalelane** [comment]
I think this was fixed in #99 so happy to close this now
